import type { Metadata } from "next";
import "./globals.css";
import "cal-sans";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Carbonne",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`dark ${roboto.className}`}>
      <body className={`font-inter antialiased`}>{children}</body>
    </html>
  );
}
